import React, { useState } from 'react';
import { Search, CheckCircle2, XCircle } from 'lucide-react';
import type { WatermarkConfig, DetectionResult, TokenItem } from '../types';

interface Props {
  selectedModel: string;
  config: WatermarkConfig;
  initialText?: string;
  onRegisterRun?: (runFn: () => void, isAnalyzing: boolean) => void;
}

const SAMPLE_TEXTS = {
  human: "Photosynthesis is a vital biological process used by plants, algae, and certain bacteria to convert light energy into chemical energy. This chemical energy is stored in carbohydrate molecules, such as sugars and starches, which are synthesized from carbon dioxide and water. Oxygen is released as a byproduct, making it essential for sustaining aerobic life on Earth.",
  tampered: "Quantum computing is a rapidly advancing area of computer science that harnesses the peculiar principles of quantum mechanics. Traditional computers process information using bits that represent either a zero or a one. In sharp contrast, quantum devices employ quantum bits or qubits, which can exist in superpositions of states."
};

export const WatermarkDetector = ({ selectedModel, config, initialText = '', onRegisterRun }: Props) => {
  const [inputText, setInputText] = useState(initialText);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [hoveredToken, setHoveredToken] = useState<TokenItem | null>(null);

  React.useEffect(() => {
    if (initialText) {
      setInputText(initialText);
    }
  }, [initialText]);

  const runDetection = React.useCallback(async () => {
    if (!inputText.trim()) return;
    setIsAnalyzing(true);
    try {
      const response = await fetch('/api/detect', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text: inputText,
          model_name: selectedModel,
          gamma: config.gamma,
          hash_key: config.hash_key,
          context_width: config.context_width,
          z_threshold: 3.0
        })
      });

      if (!response.ok) {
        throw new Error(`Detection failed: ${response.statusText}`);
      }

      const data: DetectionResult = await response.json();
      setResult(data);
    } catch (err) {
      console.error('Detection error:', err);
    } finally {
      setIsAnalyzing(false);
    }
  }, [inputText, selectedModel, config]);

  React.useEffect(() => {
    onRegisterRun?.(runDetection, isAnalyzing);
  }, [runDetection, isAnalyzing, onRegisterRun]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      <div className="panel-card">
        <div className="panel-header">
          <div>
            <h2 className="panel-title">
              <Search size={18} color="var(--brand-cyan)" />
              Watermark Detector & Verifier
            </h2>
            <p className="panel-subtitle">
              Tokenizes input text, recreates the green list partition at every step, and computes binomial significance (Z-Score).
            </p>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              className="btn-secondary"
              onClick={() => {
                setInputText(SAMPLE_TEXTS.human);
                setResult(null);
              }}
            >
              Load Human Sample
            </button>
            <button
              className="btn-secondary"
              onClick={() => {
                setInputText(SAMPLE_TEXTS.tampered);
                setResult(null);
              }}
            >
              Load Mixed Sample
            </button>
          </div>
        </div>

        <div className="control-group">
          <textarea
            className="text-area"
            style={{ minHeight: '130px', fontSize: '0.92rem' }}
            value={inputText}
            onChange={(e) => {
              setInputText(e.target.value);
              setResult(null);
            }}
            placeholder="Paste any text here to verify if it was generated by a watermarked LLM..."
          />
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <button
            className="btn-primary"
            onClick={runDetection}
            disabled={isAnalyzing || !inputText.trim()}
          >
            <Search size={16} />
            {isAnalyzing ? 'Analyzing Tokens...' : 'Analyze & Check Watermark'}
          </button>
        </div>

        {result && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px', marginTop: '8px' }}>
            <div className={`verdict-banner ${result.is_watermarked ? 'detected' : 'undetected'}`}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                {result.is_watermarked ? (
                  <CheckCircle2 size={32} color="var(--watermark-green)" />
                ) : (
                  <XCircle size={32} color="var(--text-muted)" />
                )}
                <div>
                  <div className="verdict-title">
                    {result.is_watermarked ? 'Watermark Detected!' : 'No Watermark Detected'}
                  </div>
                  <div className="verdict-desc">
                    {result.is_watermarked
                      ? `Statistical evidence strongly indicates this text was generated by a watermarked model.`
                      : `The green token distribution is consistent with natural human text or unwatermarked generation.`}
                  </div>
                </div>
              </div>
              <div className={`badge-tag ${result.is_watermarked ? 'green' : 'neutral'}`}>
                {result.confidence_level}
              </div>
            </div>

            <div className="stats-grid">
              <div className="stat-item">
                <span className="stat-label">Evaluated Transitions</span>
                <span className="stat-value">{result.evaluated_tokens}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Green Tokens</span>
                <span className="stat-value green">{result.green_tokens}</span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Actual vs Expected</span>
                <span className="stat-value green">
                  {(result.green_fraction * 100).toFixed(1)}%{' '}
                  <small style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                    / {(result.expected_fraction * 100).toFixed(0)}%
                  </small>
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">Z-Score</span>
                <span
                  className="stat-value"
                  style={{
                    color: result.z_score >= 3.0 ? 'var(--watermark-green)' : 'var(--text-primary)'
                  }}
                >
                  {result.z_score.toFixed(2)}
                </span>
              </div>
              <div className="stat-item">
                <span className="stat-label">P-Value</span>
                <span className="stat-value" style={{ fontSize: '1.05rem' }}>
                  {result.p_value < 0.0001 ? result.p_value.toExponential(2) : result.p_value.toFixed(4)}
                </span>
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
                <span style={{ fontSize: '0.85rem', fontWeight: 600, color: 'var(--text-secondary)' }}>
                  Token-by-Token Sequence Analysis
                </span>
                <div style={{ display: 'flex', gap: '12px', fontSize: '0.78rem' }}>
                  <span style={{ color: 'var(--watermark-green)' }}>● Green (In partition)</span>
                  <span style={{ color: 'var(--watermark-red)' }}>● Red (Out of partition)</span>
                  <span style={{ color: 'var(--text-muted)' }}>● Gray (Prefix context)</span>
                </div>
              </div>

              <div className="token-stream-box">
                {result.tokens.map((tok, idx) => {
                  let cls = 'unevaluated';
                  if (tok.is_green === true) cls = 'green';
                  else if (tok.is_green === false) cls = 'red';

                  return (
                    <span
                      key={idx}
                      className={`token-pill ${cls}`}
                      onMouseEnter={() => setHoveredToken(tok)}
                      onMouseLeave={() => setHoveredToken(null)}
                    >
                      {tok.text}
                    </span>
                  );
                })}
              </div>

              {/* Reserved Token Inspector Bar (prevents layout shift / cursor flickering) */}
              <div
                style={{
                  minHeight: '38px',
                  marginTop: '8px',
                  background: 'var(--bg-input)',
                  border: '1px solid var(--border-color)',
                  padding: '8px 14px',
                  borderRadius: 'var(--radius-md)',
                  fontSize: '0.8rem',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '16px',
                  color: 'var(--text-secondary)',
                  pointerEvents: 'none'
                }}
              >
                {hoveredToken ? (
                  <>
                    <span>Token: <code style={{ color: 'var(--text-primary)' }}>{JSON.stringify(hoveredToken.text)}</code></span>
                    <span>ID: <code style={{ color: 'var(--brand-cyan)' }}>{hoveredToken.id}</code></span>
                    <span>
                      Status:{' '}
                      <strong
                        style={{
                          color:
                            hoveredToken.is_green === true
                              ? 'var(--watermark-green)'
                              : hoveredToken.is_green === false
                              ? 'var(--watermark-red)'
                              : 'var(--text-muted)'
                        }}
                      >
                        {hoveredToken.is_green === true
                          ? 'GREEN (Matched partition)'
                          : hoveredToken.is_green === false
                          ? 'RED (Did not match)'
                          : 'Context Prefix'}
                      </strong>
                    </span>
                  </>
                ) : (
                  <span style={{ color: 'var(--text-muted)', fontSize: '0.78rem' }}>
                    💡 Hover over any token to inspect its ID and partition status.
                  </span>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
